AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Dips Lambda App Functions

Resources:
  GraphQL:
    Type: AWS::Serverless::Function
    Properties:
      Handler: server.graphqlHandler
      Runtime: nodejs8.10
      CodeUri: build/
      Events:
        GetRequest:
          Type: Api
          Properties:
            Path: /
            Method: get
        PostRequest:
          Type: Api
          Properties:
            Path: /
            Method: post

  # HelloWorldFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     Handler: index.handler
  #     Runtime: nodejs6.10
  #     CodeUri: src/
  #     Events:
  #       GetRequest:
  #         Type: Api
  #         Properties:
  #           Path: /
  #           Method: get

  # GraphQLInspector:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     Handler: ./src/graphql.graphiqlHandler
  #     Runtime: nodejs8.10
  #     CodeUri: '.'
  #     Events:
  #       GetRequest:
  #         Type: Api
  #         Properties:
  #           Path: /graphiql
  #           Method: get